/** Purpose : Assignment by Nikhil Sir (Create a list of integers and add ten random numbers to it. Sort the list in ascending order and print the sorted list.)

Date of create : 21/11/24

Created by : Priyank

Released Log : V1

**/
public class ClassOfListOfIntegerAndSortInAsc {
    
    public void sortTheListOfInteger(){
        List<Integer> ListOfInteger = new List<Integer>{56,78,31,55,99};
        ListOfInteger.sort();
        System.debug(ListOfInteger);
        
    }
}